### ISSUE TITLE
Ability to block search engine crawlers

### ISSUE THREAD

**Issue by dakotahp** [libreddit/libreddit#265]
## Is your feature request related to a problem? Please describe.

I did a web search for Libreddit as a shortcut to the repo one time and noticed a ton of people's instances showing up in the search. It was shocking and I like to keep my self-hosted instances under the radar when I can and have them _not_ be crawled by search engines.

## Describe the solution you'd like

I notice you render a standard robots.txt content on the fly here: https://github.com/spikecodes/libreddit/blob/master/src/main.rs#L159

I was wondering if there was an alternative with either a UI option (a bit more work) or a local volume file override (less work) for a custom robots.txt to be able to block search engine bots. 

## Additional context

This may not be a weird request but I would think a lot of people who like to self-host are also interested in keeping their private instances off of search engines for the general public to be aware of. 

Thanks

**Comment by rehashedsalt** [comment]
As a stopgap, using your favorite reverse proxy to serve a different, more restrictive `robots.txt` should work just fine. +1 either way though.

**Comment by lbrdt** [comment]
If anyone runs into a similar problem, you can use CloudFlare to overwrite the robots.txt

Details:

https://www.jucktion.com/tech/overwrite-robotstxt-cloudflare-workers/

**Comment by dennis1248** [comment]
Resolving `/robots.txt` using a reverse proxy to another server through hosting your robots.txt file is indeed the way. Here is a concrete example for Traefik specifically.

```yaml
  no-robots:
    image: httpd:latest
    restart: always
    labels:
      - "traefik.http.routers.libreddit-robots.rule=Host(`libreddit.example.com`) && Path(`/robots.txt`)"
    volumes:
    # The robots directory contains my robots.txt
      - ./robots:/usr/local/apache2/htdocs:ro
```
Besides that just append the usual stuffs such as your TLS configuration like normal.
